const PUBLIC_URL = process.env.PUBLIC_URL;

export const barajas = {
  za01: {
    nombre: "Dilla Xhon - Zoogocho",
    componible: true,
    botones: {
      ganar: "¡Loteria!",
    },
    cartas: {
      1: {
        nombre: "yelllhio",
        imagen: `${PUBLIC_URL}/images/1. LA TIERRA.webp`,
        audio: `${PUBLIC_URL}/audio/Earth.wav`,
        color: "yellow",
        id: "01",
        en: "Earth",
      },
      2: {
        nombre: "gwbill",
        imagen: `${PUBLIC_URL}/images/2. EL SOL.webp`,
        audio: `${PUBLIC_URL}/audio/Sun.wav`,
        color: "purple",
        id: "02",
        en: "Sun",
      },
      3: {
        nombre: "bio'",
        imagen: `${PUBLIC_URL}/images/3. LA LUNA.webp`,
        audio: `${PUBLIC_URL}/audio/Moon.wav`,
        color: "blue",
        id: "03",
        en: "Moon",
      },
      4: {
        nombre: "beljw",
        imagen: `${PUBLIC_URL}/images/4. LA ESTRELLA.webp`,
        audio: `${PUBLIC_URL}/audio/Star.wav`,
        color: "red",
        id: "04",
        en: "Star",
      },
      5: {
        nombre: "yaba",
        imagen: `${PUBLIC_URL}/images/5. EL CIELO.webp`,
        audio: `${PUBLIC_URL}/audio/Sky.wav`,
        color: "yellow",
        id: "05",
        en: "Sky",
      },
      6: {
        nombre: "bdoa",
        imagen: `${PUBLIC_URL}/images/6. LA CATARATA.webp`,
        audio: `${PUBLIC_URL}/audio/Cataract.wav`,
        color: "blue",
        id: "06",
        en: "Cataract",
      },
      7: {
        nombre: "bej",
        imagen: `${PUBLIC_URL}/images/7. EL POZO.webp`,
        audio: `${PUBLIC_URL}/audio/Well.wav`,
        color: "red",
        id: "07",
        en: "Well",
      },
      8: {
        nombre: "yelh",
        imagen: `${PUBLIC_URL}/images/8. LA LAGUNA.webp`,
        audio: `${PUBLIC_URL}/audio/Lagoon.wav`,
        color: "yellow",
        id: "08",
        en: "Lagoon",
      },
      9: {
        nombre: "ya'yego",
        imagen: `${PUBLIC_URL}/images/9. LA SIERRA NORTE.webp`,
        audio: `${PUBLIC_URL}/audio/The northern Sierra.wav`,
        color: "blue",
        id: "09",
        en: "The northern Sierra",
      },
      10: {
        nombre: "yag",
        imagen: `${PUBLIC_URL}/images/10. EL ÁRBOL.webp`,
        audio: `${PUBLIC_URL}/audio/Tree.wav`,
        color: "blue",
        id: "10",
        en: "Tree",
      },
      11: {
        nombre: "pita",
        imagen: `${PUBLIC_URL}/images/11. EL ARCOIRIS.webp`,
        audio: `${PUBLIC_URL}/audio/Rainbow.wav`,
        color: "yellow",
        id: "11",
        en: "Rainbow",
      },
      12: {
        nombre: "da'",
        imagen: `${PUBLIC_URL}/images/12. EL PETATE.webp`,
        audio: `${PUBLIC_URL}/audio/Bedroll.wav`,
        color: "purple",
        id: "12",
        en: "Bedroll",
      },
      13: {
        nombre: "nhisdao",
        imagen: `${PUBLIC_URL}/images/13. EL MAR.webp`,
        audio: `${PUBLIC_URL}/audio/Sea.wav`,
        color: "yellow",
        id: "13",
        en: "Sea",
      },
      14: {
        nombre: "yeldao",
        imagen: `${PUBLIC_URL}/images/14. LA LAGUNA DE GUELATAO.webp`,
        audio: `${PUBLIC_URL}/audio/Lagoon of Guelatao.wav`,
        color: "yellow",
        id: "14",
        en: "Lagoon of Guelatao",
      },
      15: {
        nombre: "beldao'",
        imagen: `${PUBLIC_URL}/images/15. EL CAMARÓN.webp`,
        audio: `${PUBLIC_URL}/audio/Shrimp.wav`,
        color: "red",
        id: "15",
        en: "Shrimp",
      },
      16: {
        nombre: "shojtao",
        imagen: `${PUBLIC_URL}/images/16. LA TARANTULA.webp`,
        audio: `${PUBLIC_URL}/audio/Tarantula.wav`,
        color: "red",
        id: "16",
        en: "Tarantula",
      },
      17: {
        nombre: "bell",
        imagen: `${PUBLIC_URL}/images/17. EL JAGUAR.webp`,
        audio: `${PUBLIC_URL}/audio/Jaguar.wav`,
        color: "purple",
        id: "17",
        en: "Jaguar",
      },
      18: {
        nombre: "yelh",
        imagen: `${PUBLIC_URL}/images/18. MATA DE MAÍZ.webp`,
        audio: `${PUBLIC_URL}/audio/Corn Plant.wav`,
        color: "purple",
        id: "18",
        en: "Corn Plant",
      },
      19: {
        nombre: "yez",
        imagen: `${PUBLIC_URL}/images/19. LA MAZORCA.webp`,
        audio: `${PUBLIC_URL}/audio/Cob.wav`,
        color: "yellow",
        id: "19",
        en: "Cob",
      },
      20: {
        nombre: "xhoa'",
        imagen: `${PUBLIC_URL}/images/20. LOS GRANOS DE MAÍZ.webp`,
        audio: `${PUBLIC_URL}/audio/Corn Kernels.wav`,
        color: "purple",
        id: "20",
        en: "Corn Kernels",
      },
      21: {
        nombre: "yan",
        imagen: `${PUBLIC_URL}/images/21. EL OLOTE.webp`,
        audio: `${PUBLIC_URL}/audio/Corn.wav`,
        color: "blue",
        id: "21",
        en: "Corn",
      },
      22: {
        nombre: "dao",
        imagen: `${PUBLIC_URL}/images/22. LA ESPIGA DE MAÍZ.webp`,
        audio: `${PUBLIC_URL}/audio/Corn Tassel.wav`,
        color: "yellow",
        id: "22",
        en: "Corn Tassel",
      },
      23: {
        nombre: "yo'oba",
        imagen: `${PUBLIC_URL}/images/23. MITLA.webp`,
        audio: `${PUBLIC_URL}/audio/Mitla.wav`,
        color: "purple",
        id: "23",
        en: "Mitla",
      },
      24: {
        nombre: "yalban",
        imagen: `${PUBLIC_URL}/images/24. MONTE ALBAN.webp`,
        audio: `${PUBLIC_URL}/audio/Monte Alban.wav`,
        color: "red",
        id: "24",
        en: "Monte Alban",
      },
      25: {
        nombre: "bllijw",
        imagen: `${PUBLIC_URL}/images/25. LA CHIRIMIA.webp`,
        audio: `${PUBLIC_URL}/audio/chirimia.wav`,
        color: "yellow",
        id: "25",
        en: "chirimia",
      },
      26: {
        nombre: "nicachi",
        imagen: `${PUBLIC_URL}/images/26. EL TAMBOR.webp`,
        audio: `${PUBLIC_URL}/audio/Drum.wav`,
        color: "purple",
        id: "26",
        en: "Drum",
      },
      27: {
        nombre: "weya'a-binholhe",
        imagen: `${PUBLIC_URL}/images/27. LA DANZA DE LA MALINCHE.webp`,
        audio: `${PUBLIC_URL}/audio/Malinche dance.wav`,
        color: "yellow",
        id: "27",
        en: "Malinche dance",
      },
      28: {
        nombre: "gwbej",
        imagen: `${PUBLIC_URL}/images/28. LA COA.webp`,
        audio: `${PUBLIC_URL}/audio/Hoe.wav`,
        color: "blue",
        id: "28",
        en: "Hoe",
      },
      29: {
        nombre: "xtobia",
        imagen: `${PUBLIC_URL}/images/29. LA TELARAÑA.webp`,
        audio: `${PUBLIC_URL}/audio/Spiderweb.wav`,
        color: "yellow",
        id: "29",
        en: "Spiderweb",
      },
      30: {
        nombre: "berinke'",
        imagen: `${PUBLIC_URL}/images/30. LA MARIPOSA.webp`,
        audio: `${PUBLIC_URL}/audio/Butterfly.wav`,
        color: "yellow",
        id: "30",
        en: "Butterfly",
      },
      31: {
        nombre: "beza'",
        imagen: `${PUBLIC_URL}/images/31. LA ZORRA.webp`,
        audio: `${PUBLIC_URL}/audio/Fox.wav`,
        color: "purple",
        id: "31",
        en: "Fox",
      },
      32: {
        nombre: "bllinha'-yixe'",
        imagen: `${PUBLIC_URL}/images/32. EL VENADO.webp`,
        audio: `${PUBLIC_URL}/audio/Deer.wav`,
        color: "red",
        id: "32",
        en: "Deer",
      },
      33: {
        nombre: "bsia",
        imagen: `${PUBLIC_URL}/images/33. EL ÁGUILA.webp`,
        audio: `${PUBLIC_URL}/audio/Eagle.wav`,
        color: "blue",
        id: "33",
        en: "Eagle",
      },
      34: {
        nombre: "xbanyid",
        imagen: `${PUBLIC_URL}/images/34. EL TLACUACHE.webp`,
        audio: `${PUBLIC_URL}/audio/Opossum.wav`,
        color: "blue",
        id: "34",
        en: "Opossum",
      },
      35: {
        nombre: "beko'",
        imagen: `${PUBLIC_URL}/images/35. EL PERRO.webp`,
        audio: `${PUBLIC_URL}/audio/Dog.wav`,
        color: "red",
        id: "35",
        en: "Dog",
      },
      36: {
        nombre: "biz",
        imagen: `${PUBLIC_URL}/images/36. EL GATO.webp`,
        audio: `${PUBLIC_URL}/audio/Cat.wav`,
        color: "red",
        id: "36",
        en: "Cat",
      },
      37: {
        nombre: "jia",
        imagen: `${PUBLIC_URL}/images/37. EL GALLO.webp`,
        audio: `${PUBLIC_URL}/audio/Rooster.wav`,
        color: "blue",
        id: "37",
        en: "Rooster",
      },
      38: {
        nombre: "bxhobyi'",
        imagen: `${PUBLIC_URL}/images/38. LA VIUDA NEGRA.webp`,
        audio: `${PUBLIC_URL}/audio/Black Widow.wav`,
        color: "red",
        id: "38",
        en: "Black Widow",
      },
      39: {
        nombre: "bexjonhi'",
        imagen: `${PUBLIC_URL}/images/39. EL ALACRÁN.webp`,
        audio: `${PUBLIC_URL}/audio/Scorpion.wav`,
        color: "purple",
        id: "39",
        en: "Scorpion",
      },
      40: {
        nombre: "yetgo'-za",
        imagen: `${PUBLIC_URL}/images/40. EL TAMAL DE FRIJOL.webp`,
        audio: `${PUBLIC_URL}/audio/Black Bean Tamal.wav`,
        color: "red",
        id: "40",
        en: "Black Bean Tamal",
      },
      41: {
        nombre: "yet",
        imagen: `${PUBLIC_URL}/images/41. LA TORTILLA.webp`,
        audio: `${PUBLIC_URL}/audio/Tortilla.wav`,
        color: "red",
        id: "41",
        en: "Tortilla",
      },
      42: {
        nombre: "yetxtilh",
        imagen: `${PUBLIC_URL}/images/42. EL PAN.webp`,
        audio: `${PUBLIC_URL}/audio/Bread.wav`,
        color: "red",
        id: "42",
        en: "Bread",
      },
      43: {
        nombre: "wene-ya'a",
        imagen: `${PUBLIC_URL}/images/43. EL ADIVINO.webp`,
        audio: `${PUBLIC_URL}/audio/fortune teller.wav`,
        color: "purple",
        id: "43",
        en: "fortune teller",
      },
      44: {
        nombre: "bibe'",
        imagen: `${PUBLIC_URL}/images/44. LA JOJOBA.webp`,
        audio: `${PUBLIC_URL}/audio/Jojoba.wav`,
        color: "red",
        id: "44",
        en: "Jojoba",
      },
      45: {
        nombre: "ye'n-yo",
        imagen: `${PUBLIC_URL}/images/45. EL PLATO DE BARRO.webp`,
        audio: `${PUBLIC_URL}/audio/Clay Plate.wav`,
        color: "yellow",
        id: "45",
        en: "Clay Plate",
      },
      46: {
        nombre: "yela'",
        imagen: `${PUBLIC_URL}/images/46. EL PLÁTANO.webp`,
        audio: `${PUBLIC_URL}/audio/Banana.wav`,
        color: "blue",
        id: "46",
        en: "Banana",
      },
      47: {
        nombre: "wiyej",
        imagen: `${PUBLIC_URL}/images/47. LA GUAYABA.webp`,
        audio: `${PUBLIC_URL}/audio/Guava.wav`,
        color: "purple",
        id: "47",
        en: "Guava",
      },
      48: {
        nombre: "nazia'",
        imagen: `${PUBLIC_URL}/images/48. EL CAPULÍN.webp`,
        audio: `${PUBLIC_URL}/audio/Capulin.wav`,
        color: "blue",
        id: "48",
        en: "capulin",
      },
      49: {
        nombre: "pasonga'",
        imagen: `${PUBLIC_URL}/images/49. EL POZONTLE.webp`,
        audio: `${PUBLIC_URL}/audio/Pozontle.wav`,
        color: "blue",
        id: "49",
        en: "Pozontle",
      },
      50: {
        nombre: "wi",
        imagen: `${PUBLIC_URL}/images/50. LA NARANJA.webp`,
        audio: `${PUBLIC_URL}/audio/Orange.wav`,
        color: "blue",
        id: "50",
        en: "Orange",
      },
      51: {
        nombre: "xhaga'",
        imagen: `${PUBLIC_URL}/images/51. LA BLUSA.webp`,
        audio: `${PUBLIC_URL}/audio/Blouse.wav`,
        color: "blue",
        id: "51",
        en: "Blouse",
      },
      52: {
        nombre: "zode'",
        imagen: `${PUBLIC_URL}/images/52. LA FALDA.webp`,
        audio: `${PUBLIC_URL}/audio/Skirt.wav`,
        color: "red",
        id: "52",
        en: "Skirt",
      },
      53: {
        nombre: "bekoxho'",
        imagen: `${PUBLIC_URL}/images/53. EL REBOZO.webp`,
        audio: `${PUBLIC_URL}/audio/Shawl.wav`,
        color: "red",
        id: "53",
        en: "Shawl",
      },
      54: {
        nombre: "bayw",
        imagen: `${PUBLIC_URL}/images/54. EL PAÑUELO.webp`,
        audio: `${PUBLIC_URL}/audio/Handkerchief.wav`,
        color: "yellow",
        id: "54",
        en: "Handkerchief",
      },
      55: {
        nombre: "bio'",
        imagen: `${PUBLIC_URL}/images/55. LA MÁSCARA.webp`,
        audio: `${PUBLIC_URL}/audio/Mask.wav`,
        color: "purple",
        id: "55",
        en: "Mask",
      },
      56: {
        nombre: "webej-sheb",
        imagen: `${PUBLIC_URL}/images/56. LA PERSONA QUE SACA EL SUSTO.webp`,
        audio: `${PUBLIC_URL}/audio/Curandero.wav`,
        color: "blue",
        id: "56",
        en: "Curandero",
      },
      57: {
        nombre: "ngolh",
        imagen: `${PUBLIC_URL}/images/57. EL GUAJOLOTE.webp`,
        audio: `${PUBLIC_URL}/audio/Turkey.wav`,
        color: "yellow",
        id: "57",
        en: "Turkey",
      },
    },
  },
  // es01: {
  //   nombre: "español de MX",
  //   componible: false,
  //   botones: {
  //     ganar: "¡lotería!",
  //   },
  //   cartas: {
  //     "01": {
  //       nombre: "el gallo",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/01-gallo.jpg",
  //       audio: "",
  //     },
  //     "02": {
  //       nombre: "el diablito",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/02-diablito.jpg",
  //       audio: "",
  //     },
  //     "03": {
  //       nombre: "la dama",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/03-dama.jpg",
  //       audio: "",
  //     },
  //     "04": {
  //       nombre: "el catrín",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/04-catrin.jpg",
  //       audio: "",
  //     },
  //     "05": {
  //       nombre: "el paraguas",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/05-paraguas.jpg",
  //       audio: "",
  //     },
  //     "06": {
  //       nombre: "la sirena",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/06-sirena.jpg",
  //       audio: "",
  //     },
  //     "07": {
  //       nombre: "la escalera",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/07-escalera.jpg",
  //       audio: "",
  //     },
  //     "08": {
  //       nombre: "la botella",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/08-botella.jpg",
  //       audio: "",
  //     },
  //     "09": {
  //       nombre: "el barril",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/09-barril.jpg",
  //       audio: "",
  //     },
  //     10: {
  //       nombre: "el árbol",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/10-arbol.jpg",
  //       audio: "",
  //     },
  //     11: {
  //       nombre: "el melón",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/11-melon.jpg",
  //       audio: "",
  //     },
  //     12: {
  //       nombre: "el valiente",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/12-valiente.jpg",
  //       audio: "",
  //     },
  //     13: {
  //       nombre: "el gorrito",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/13-gorrito.jpg",
  //       audio: "",
  //     },
  //     14: {
  //       nombre: "la muerte",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/14-muerte.jpg",
  //       audio: "",
  //     },
  //     15: {
  //       nombre: "la pera",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/15-pera.jpg",
  //       audio: "",
  //     },
  //     16: {
  //       nombre: "la bandera",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/16-bandera.jpg",
  //       audio: "",
  //     },
  //     17: {
  //       nombre: "el bandolón",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/17-bandolon.jpg",
  //       audio: "",
  //     },
  //     18: {
  //       nombre: "el violoncello",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/18-violoncello.jpg",
  //       audio: "",
  //     },
  //     19: {
  //       nombre: "la garza",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/19-garza.jpg",
  //       audio: "",
  //     },
  //     20: {
  //       nombre: "el pájaro",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/20-pajaro.jpg",
  //       audio: "",
  //     },
  //     21: {
  //       nombre: "la mano",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/21-mano.jpg",
  //       audio: "",
  //     },
  //     22: {
  //       nombre: "la bota",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/22-bota.jpg",
  //       audio: "",
  //     },
  //     23: {
  //       nombre: "la luna",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/23-luna.jpg",
  //       audio: "",
  //     },
  //     24: {
  //       nombre: "el cotorro",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/24-cotorro.jpg",
  //       audio: "",
  //     },
  //     25: {
  //       nombre: "el borracho",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/25-borracho.jpg",
  //       audio: "",
  //     },
  //     // 26: {
  //     //   nombre: "el negrito",
  //     //   imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/26-negrito.jpg",
  //     //   audio: "",
  //     // },
  //     27: {
  //       nombre: "el corazón",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/27-corazon.jpg",
  //       audio: "",
  //     },
  //     28: {
  //       nombre: "la sandía",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/28-sandia.jpg",
  //       audio: "",
  //     },
  //     29: {
  //       nombre: "el tambor",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/29-tambor.jpg",
  //       audio: "",
  //     },
  //     30: {
  //       nombre: "el camarón",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/30-camaron.jpg",
  //       audio: "",
  //     },
  //     31: {
  //       nombre: "las jaras",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/31-jaras.jpg",
  //       audio: "",
  //     },
  //     32: {
  //       nombre: "el músico",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/32-musico.jpg",
  //       audio: "",
  //     },
  //     33: {
  //       nombre: "la araña",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/33-arana.jpg",
  //       audio: "",
  //     },
  //     34: {
  //       nombre: "el soldado",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/34-soldado.jpg",
  //       audio: "",
  //     },
  //     35: {
  //       nombre: "la estrella",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/35-estrella.jpg",
  //       audio: "",
  //     },
  //     36: {
  //       nombre: "el cazo",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/36-cazo.jpg",
  //       audio: "",
  //     },
  //     37: {
  //       nombre: "el mundo",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/37-mundo.jpg",
  //       audio: "",
  //     },
  //     // 38: {
  //     //   nombre: "el apache",
  //     //   imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/38-apache.jpg",
  //     //   audio: "",
  //     // },
  //     39: {
  //       nombre: "el nopal",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/39-nopal.jpg",
  //       audio: "",
  //     },
  //     40: {
  //       nombre: "el alacrán",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/40-alacran.jpg",
  //       audio: "",
  //     },
  //     41: {
  //       nombre: "la rosa",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/41-rosa.jpg",
  //       audio: "",
  //     },
  //     42: {
  //       nombre: "la calavera",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/42-calavera.jpg",
  //       audio: "",
  //     },
  //     43: {
  //       nombre: "la campana",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/43-campana.jpg",
  //       audio: "",
  //     },
  //     44: {
  //       nombre: "el cantarito",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/44-cantarito.jpg",
  //       audio: "",
  //     },
  //     45: {
  //       nombre: "el venado",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/45-venado.jpg",
  //       audio: "",
  //     },
  //     46: {
  //       nombre: "el sol",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/46-sol.jpg",
  //       audio: "",
  //     },
  //     47: {
  //       nombre: "la corona",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/47-corona.jpg",
  //       audio: "",
  //     },
  //     48: {
  //       nombre: "la chalupa",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/48-chalupa.jpg",
  //       audio: "",
  //     },
  //     49: {
  //       nombre: "el pino",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/49-pino.jpg",
  //       audio: "",
  //     },
  //     50: {
  //       nombre: "el pescado",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/50-pescado.jpg",
  //       audio: "",
  //     },
  //     51: {
  //       nombre: "la palma",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/51-palma.jpg",
  //       audio: "",
  //     },
  //     52: {
  //       nombre: "la maceta",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/52-maceta.jpg",
  //       audio: "",
  //     },
  //     53: {
  //       nombre: "el arpa",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/53-arpa.jpg",
  //       audio: "",
  //     },
  //     54: {
  //       nombre: "la rana",
  //       imagen: "https://storage.googleapis.com/loteria-cielo/barajas/es-mx/54-rana.jpg",
  //       audio: "",
  //     },
  //   },
  // },
};
